---
name: Molecule Test
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      # - name: Set up Python ${{ matrix.python-version }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # python-version: ${{ matrix.python-version }}
          python-version: 3.8
      - name: Install dependencies
        run: |
          make create-venv
      - name: Test with molecule
        run: |
          . .venv/bin/activate
          molecule test
      - name: Import role to Ansible Galaxy`
        uses: 0x022b/galaxy-role-import-action@v1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
